### CREATE A NEW BOOK

POST http://localhost:3000/books
Content-Type: application/json


{
  "title": "the reacher",
  "author": "John",
  "published_year": 2015,
  "isbn": 7801345166,
  "isAvailable": true
}

####      GET ALL BOOKS 
GET http://localhost:3000/books

### get one
GET http://localhost:3000/books/1
###update
patch http://localhost:3000/books/1


{
  "title" :"the reacher"
}
###delete book by id
DELETE http://localhost:3000/books/1