### CREATE A NEW BOOK

POST http://localhost:3000/books
Content-Type: application/json


{
  "title": "The ME",
  "author": "ALBERT",
  "published_year": 2022,
  "isbn": 78016795166,
  "isAvailable": true
}

####      GET ALL BOOKS 
GET http://localhost:3000/books

### get one
GET http://localhost:3000/books/10
###update
patch http://localhost:3000/books/1


{
  "title" :"the reacher"
}
###delete book by id
DELETE http://localhost:3000/books/9