CREATE OR REPLACE FUNCTION SP_SOFT_DELETE_BOOOKS(p_id INTEGER)
RETURNS TABLE(
      success BOOLEAN,
      message text,
     TITLE VARCHAR(255)
)as $$ 
DECLARE 

current_title VARCHAR(255) 
BEGIN 

SELECT BOOKS.TITLE INTO current_title FROM BOOKS WHERE BOOKS.ID AND BOOKS.iD_available = TRUE

IF NOT FOUND THEN

RAISE EXCEPTION 'BOOK WITH ID % NOT FOUND ' P_id;
END IF;

UPDATE BOOKS SET is_available = FALSE WHERE BOOKS.ID = P.ID;

RETURN QUERY SELECT TRUE, 'BOOK ' || current_title || 'HAS CHECKED OUT SUCCESSFULLY', current_title;
END;
$$ language plpgsql;





CREATE OR REPLACE FUNCTION SP_SOFT_DELETE_BOOOKS(p_id INTEGER)
RETURNS TABLE(
      success BOOLEAN,
      message text,
     TITLE VARCHAR(255)
)as $$ 
DECLARE 

DELETED_title VARCHAR(255) 
BEGIN 

SELECT BOOKS.TITLE INTO current_title FROM BOOKS WHERE BOOKS.ID = P_id 

IF NOT FOUND THEN

RAISE EXCEPTION 'BOOK WITH ID % NOT FOUND ' P_id;
END IF;


DELETE FROM BOOKS WHERE BOOKS.ID = P_id;

RETURN QUERY SELECT TRUE, 'BOOK ' || current_title || 'HAS BEEN  PERMANENTLY DELETED ', DELETED_title;
END;
$$ language plpgsql;

